name: Continuous Integration
run-name: Continuous Integration
on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: npm install
      - name: Run Prettier & ESLint
        run: npm run prettier
      - name: Run ESLint
        run: npm run lint
      - name: Build application
        run: npm run build
      - run: echo "This job's status is ${{ job.status }}."

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://webpack-html-sass-js.vercel.app'
